<?php
define("EMAIL_ADMIN","Please contact the administrator of this site: ");
define("P_ERR_CONNECTION","Database server CONNECTION error.");
define("P_ERR_OPEN_LOG","Error open a log file.");
define("L_ERR_CONNECTION","Database server CONNECTION error ");
define("L_SCS_CONNECTION","Database server connection succesfull");
define("P_SCS_CONNECTION","Database server connection succesfull.");
define("P_ERR_SELECTDB","Unable to SELECT database.");
define("L_ERR_SELECTDB","Unable to SELECT database ");
define("L_SCS_SELECTDB","Database select succesfull");
define("P_SCS_SELECTDB","Database select succesfull.");
define("L_SCS_CLOSE","Close database succesfull");
define("P_ERR_SQLSELECT","Database SINTAX SQL SELECT error");
define("L_ERR_SQLSELECT","Database SINTAX SQL SELECT error");
define("L_SCS_SQLSELECT","Database sql select succesfull");
define("P_ERR_SELECT","Database SQL SELECT error");
define("L_ERR_EXECUTE","Error EXECUTE ");
define("L_SCS_EXECUTE","Execute Succesfull");
?>